# Generated by Django 4.0.5 on 2022-10-01 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VideoQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_price', models.IntegerField()),
                ('yearly_price', models.IntegerField()),
                ('devices', models.ManyToManyField(to='subscription.device')),
                ('plan_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.plantype')),
                ('resolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.resolution')),
                ('video_quality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.videoquality')),
            ],
        ),
    ]
