# Generated by Django 4.0.5 on 2022-10-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_device_resolution_videoquality_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='resolution',
            name='resolution',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='videoquality',
            name='quality',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
